use_frameworks!

platform :ios, '8.0'

target 'DYCommonNetwork_Example' do
  pod 'DYCommonNetwork', :path => '../'

  target 'DYCommonNetwork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
